influx:
    url: http://localhost:8086
    org: ioteatime
    bucket: ioteatime
    token: qMAlqYdeo8KGX-wgL2M_gsBnzOtuHOspsop_rKUGdOecR4DUMM_EKdrQ248f9xTg5doSSepz4Z_fOejehCtMUA==

mqtt:
    uri: tcp://133.186.153.19:1883
    id: test
    topics:
        - data/s/nhnacademy/b/gyeongnam/p/+/d/gems-3500/e/+/t/+/ph/+/de/#
