influx:
    url: ${{ secrets.INFLUXDB_IP }}
    org: ${{ secrets.INFLUXDB_ORG }}
    bucket: ${{ secrets.INFLUXDB_BUCKET }}
    token: ${{ secrets.INFLUXDB_TOKEN }}


my:
    rabbitmq:
        host: ${{ secrets.RABBITMQ_IP }}
        port: ${{ secrets.RABBITMQ_PORT }}
        username: ${{ secrets.RABBITMQ_USERNAME }}
        password: ${{ secrets.RABBITMQ_PW }}

